-- CreateTable
CREATE TABLE "structure_ids" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "structureNumber" VARCHAR(50),
    "structureName" VARCHAR(200),
    "structureMarking" VARCHAR(100),
    "generalDescription" TEXT,
    "area" VARCHAR(10),
    "belongsToRoad" VARCHAR(10),
    "runningDistanceKm" VARCHAR(10),
    "runningDistanceStart" VARCHAR(10),
    "runningDistanceEnd" VARCHAR(10),
    "coordinateNorth" VARCHAR(10),
    "coordinateEast" VARCHAR(10),
    "primaryClassificationGroup" VARCHAR(10),
    "secondaryClassificationGroup" VARCHAR(10),
    "trafficFunctionClass" VARCHAR(10),
    "emergencyClass" VARCHAR(10),
    "builtBy" VARCHAR(10),
    "owner" VARCHAR(10),
    "maintenanceResponsibility" VARCHAR(10),
    "tollRoad" VARCHAR(10),
    "specialTransport" VARCHAR(10),
    "historicalValue" VARCHAR(10),
    "temporaryStructure" VARCHAR(10),
    "constructionYear" VARCHAR(4),
    "lastRehabYear" VARCHAR(4),
    "primaryUsageAbove" VARCHAR(10),
    "primaryRoadNumberAbove" VARCHAR(10),
    "secondaryUsageAbove" VARCHAR(10),
    "secondaryRoadNumberAbove" VARCHAR(10),
    "tracksOrRailwaysAbove" INTEGER,
    "lanesAbove" INTEGER,
    "trafficDirectionAbove" VARCHAR(10),
    "primaryUsageBelow" VARCHAR(10),
    "primaryRoadNumberBelow" VARCHAR(10),
    "secondaryUsageBelow" VARCHAR(10),
    "secondaryRoadNumberBelow" VARCHAR(10),
    "tracksOrRailwaysBelow" INTEGER,
    "lanesBelow" INTEGER,
    "trafficDirectionBelow" VARCHAR(10),
    "aadt" INTEGER,
    "aadtYear" VARCHAR(4),
    "aadtt" INTEGER,
    "bypassPossible" VARCHAR(10),
    "bypassLength" INTEGER,
    "bypassDescription" TEXT,
    "localBypass" VARCHAR(10),
    "localBypassMethod" VARCHAR(10),
    "originalPlanner" VARCHAR(200),
    "rehabPlanner" VARCHAR(200),
    "spanCount" INTEGER,
    "maxSpanLength" DOUBLE PRECISION,
    "totalLength" DOUBLE PRECISION,
    "lengthRight" DOUBLE PRECISION,
    "lengthLeft" DOUBLE PRECISION,
    "spanDistribution" VARCHAR(500),
    "widthChange" VARCHAR(10),
    "minWidthPerpendicular" DOUBLE PRECISION,
    "maxWidthPerpendicular" DOUBLE PRECISION,
    "maxExternalWidth" DOUBLE PRECISION,
    "minExternalWidth" DOUBLE PRECISION,
    "rightSidewalkWidth" DOUBLE PRECISION,
    "leftSidewalkWidth" DOUBLE PRECISION,
    "minRoadwayWidth" DOUBLE PRECISION,
    "totalRoadwayWidth" DOUBLE PRECISION,
    "separatorType" VARCHAR(10),
    "skewAngle" INTEGER,
    "minVerticalClearanceBelow" DOUBLE PRECISION,
    "verticalClearanceDrainage" DOUBLE PRECISION,
    "minVerticalClearanceAbove" DOUBLE PRECISION,
    "heightSignageValue" DOUBLE PRECISION,
    "minHorizontalClearance" DOUBLE PRECISION,
    "maxPierHeight" DOUBLE PRECISION,
    "maxWallHeight" DOUBLE PRECISION,
    "avgJointSpacing" DOUBLE PRECISION,
    "minDistanceYellowLineTop" DOUBLE PRECISION,
    "minDistanceYellowLineBottom" DOUBLE PRECISION,
    "wallFaceArea" DOUBLE PRECISION,
    "deckArea" DOUBLE PRECISION,
    "maxTheoreticalVerticalDim" DOUBLE PRECISION,
    "maxHorizontalDim" DOUBLE PRECISION,
    "minVerticalClearanceTunnel" DOUBLE PRECISION,
    "minHorizontalClearanceTunnel" DOUBLE PRECISION,
    "deckTypeCount" INTEGER,
    "deckTypes" TEXT,
    "floorType" TEXT,
    "abutment1Type" VARCHAR(10),
    "abutment2Type" VARCHAR(10),
    "pierTypeCount" INTEGER,
    "pierTypes" TEXT,
    "prestressingType" VARCHAR(10),
    "bearingTypes" TEXT,
    "jointTypes" TEXT,
    "deckMaterials" TEXT,
    "beamMaterials" TEXT,
    "abutmentMaterials" TEXT,
    "pierMaterials" TEXT,
    "slopeProtectionMaterials" TEXT,
    "vehicleBarrierMaterials" TEXT,
    "pedestrianRailingMaterials" TEXT,
    "deckCoveringMaterials" TEXT,
    "deckSealingMaterials" TEXT,
    "curbMaterials" TEXT,
    "loadRatingMethod" TEXT,
    "loadRatingResult" VARCHAR(100),
    "loadRatingDate" TIMESTAMP(3),
    "seismicRatingMethod" TEXT,
    "seismicRatingResult" VARCHAR(100),
    "seismicRatingDate" TIMESTAMP(3),
    "approvedLoadLimits" INTEGER,
    "loadSignage" INTEGER,
    "infrastructureTypes" TEXT,
    "maxRelativeLevel" DOUBLE PRECISION,
    "designReturnPeriod" INTEGER,
    "hydraulicAdequacy" VARCHAR(10),
    "conditionPIav" INTEGER,
    "conditionPIcrit" INTEGER,
    "availabilityPI" INTEGER,
    "reliabilityPI" INTEGER,
    "inspectionClassification" VARCHAR(20),
    "initialInspectionDate" TIMESTAMP(3),
    "lastRoutineInspectionDate" TIMESTAMP(3),
    "routineInspectionFrequency" INTEGER,
    "damageControlInspectionDate" TIMESTAMP(3),
    "underwaterInspectionDate" TIMESTAMP(3),
    "thoroughInspectionDate" TIMESTAMP(3),
    "specialInspectionDate" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "structure_ids_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "structure_ids" ADD CONSTRAINT "structure_ids_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
